purchase_type: on_demand
subnet_id: subnet-759aee10
price: 0.13
num_instances: 5
key_name: k-schmidt
security_group_ids: sg-3eb8b940
instance_type: m4.large
tag_name: cassandra-db
vol_size: 100
role: worker
use_eips: true
